name: nxcar
version: 1.0.0+1
publish_to: none
description: Test project.
environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  dots_indicator: ^3.0.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/notosans/NotoSans.ttf
